// Generated by gencpp from file mavros_msgs/CommandAckRequest.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDACKREQUEST_H
#define MAVROS_MSGS_MESSAGE_COMMANDACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros_msgs
{
template <class ContainerAllocator>
struct CommandAckRequest_
{
  typedef CommandAckRequest_<ContainerAllocator> Type;

  CommandAckRequest_()
    : command(0)
    , result(0)
    , progress(0)
    , result_param2(0)  {
    }
  CommandAckRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , result(0)
    , progress(0)
    , result_param2(0)  {
  (void)_alloc;
    }



   typedef uint16_t _command_type;
  _command_type command;

   typedef uint8_t _result_type;
  _result_type result;

   typedef uint8_t _progress_type;
  _progress_type progress;

   typedef uint32_t _result_param2_type;
  _result_param2_type result_param2;





  typedef boost::shared_ptr< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommandAckRequest_

typedef ::mavros_msgs::CommandAckRequest_<std::allocator<void> > CommandAckRequest;

typedef boost::shared_ptr< ::mavros_msgs::CommandAckRequest > CommandAckRequestPtr;
typedef boost::shared_ptr< ::mavros_msgs::CommandAckRequest const> CommandAckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::CommandAckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::CommandAckRequest_<ContainerAllocator1> & lhs, const ::mavros_msgs::CommandAckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.result == rhs.result &&
    lhs.progress == rhs.progress &&
    lhs.result_param2 == rhs.result_param2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::CommandAckRequest_<ContainerAllocator1> & lhs, const ::mavros_msgs::CommandAckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1972b10ca14298d11f768e548d4d9e68";
  }

  static const char* value(const ::mavros_msgs::CommandAckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1972b10ca14298d1ULL;
  static const uint64_t static_value2 = 0x1f768e548d4d9e68ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/CommandAckRequest";
  }

  static const char* value(const ::mavros_msgs::CommandAckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Generic COMMAND_ACK\n"
"\n"
"uint16 command\n"
"uint8 result\n"
"uint8 progress\n"
"uint32 result_param2\n"
"\n"
;
  }

  static const char* value(const ::mavros_msgs::CommandAckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.result);
      stream.next(m.progress);
      stream.next(m.result_param2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandAckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::CommandAckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::CommandAckRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.command);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.progress);
    s << indent << "result_param2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result_param2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_COMMANDACKREQUEST_H
