// Generated by gencpp from file mavros_msgs/ESCTelemetry.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_ESCTELEMETRY_H
#define MAVROS_MSGS_MESSAGE_ESCTELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mavros_msgs/ESCTelemetryItem.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct ESCTelemetry_
{
  typedef ESCTelemetry_<ContainerAllocator> Type;

  ESCTelemetry_()
    : header()
    , esc_telemetry()  {
    }
  ESCTelemetry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , esc_telemetry(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mavros_msgs::ESCTelemetryItem_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mavros_msgs::ESCTelemetryItem_<ContainerAllocator> >::other >  _esc_telemetry_type;
  _esc_telemetry_type esc_telemetry;





  typedef boost::shared_ptr< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> const> ConstPtr;

}; // struct ESCTelemetry_

typedef ::mavros_msgs::ESCTelemetry_<std::allocator<void> > ESCTelemetry;

typedef boost::shared_ptr< ::mavros_msgs::ESCTelemetry > ESCTelemetryPtr;
typedef boost::shared_ptr< ::mavros_msgs::ESCTelemetry const> ESCTelemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::ESCTelemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::ESCTelemetry_<ContainerAllocator1> & lhs, const ::mavros_msgs::ESCTelemetry_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.esc_telemetry == rhs.esc_telemetry;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::ESCTelemetry_<ContainerAllocator1> & lhs, const ::mavros_msgs::ESCTelemetry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b1fb252ca6aa175fe8dd23d029b3362";
  }

  static const char* value(const ::mavros_msgs::ESCTelemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b1fb252ca6aa175ULL;
  static const uint64_t static_value2 = 0xfe8dd23d029b3362ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/ESCTelemetry";
  }

  static const char* value(const ::mavros_msgs::ESCTelemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# APM ESC Telemetry as returned by BLHeli\n"
"#\n"
"# See:\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12\n"
"\n"
"std_msgs/Header header\n"
"\n"
"mavros_msgs/ESCTelemetryItem[] esc_telemetry\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mavros_msgs/ESCTelemetryItem\n"
"# APM ESC Telemetry as returned by BLHeli\n"
"#\n"
"# See:\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8\n"
"# https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12\n"
"\n"
"std_msgs/Header header\n"
"\n"
"float32 temperature     # deg C\n"
"float32 voltage         # V\n"
"float32 current         # A\n"
"float32 totalcurrent    # Ah\n"
"int32 rpm               # -1/min\n"
"uint16 count            # count of telemetry packets\n"
;
  }

  static const char* value(const ::mavros_msgs::ESCTelemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.esc_telemetry);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ESCTelemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::ESCTelemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::ESCTelemetry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "esc_telemetry[]" << std::endl;
    for (size_t i = 0; i < v.esc_telemetry.size(); ++i)
    {
      s << indent << "  esc_telemetry[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mavros_msgs::ESCTelemetryItem_<ContainerAllocator> >::stream(s, indent + "    ", v.esc_telemetry[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_ESCTELEMETRY_H
