(cl:in-package mavros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FIX_TYPE-VAL
          FIX_TYPE
          GPS_ID-VAL
          GPS_ID
          IGNORE_FLAGS-VAL
          IGNORE_FLAGS
          TIME_WEEK_MS-VAL
          TIME_WEEK_MS
          TIME_WEEK-VAL
          TIME_WEEK
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          VN-VAL
          VN
          VE-VAL
          VE
          VD-VAL
          VD
          SPEED_ACCURACY-VAL
          SPEED_ACCURACY
          HORIZ_ACCURACY-VAL
          HORIZ_ACCURACY
          VERT_ACCURACY-VAL
          VERT_ACCURACY
          SATELLITES_VISIBLE-VAL
          SATELLITES_VISIBLE
          YAW-VAL
          YAW
))