name: Python checks
on:
  push:
      paths:
      - "**.py"
jobs:
    run-linters:
      name: Run linters
      runs-on: ubuntu-latest

      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install Python dependencies
          run: pip install black flake8

        - name: Run linters
          uses: wearerequired/lint-action@v1
          with:
            github_token: ${{ secrets.github_token }}
            # Enable linters
            flake8: true
            flake8_args: "--select=E9,F63,F72,F82"
    build:
      name: Update Requirements
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Check simulation_py requirements
          id: reqs_sim
          uses: afonsoVale/pipreqs-action@master
          with:
            PROJECT_PATH: ./simulation_py   #default is the root of the repository
            REQUIREMENT_PATH: ./simulation_py/requirements.txt  #default is requirement.txt in the root of your repository
            PROJECT_NAME: simulation_py 
        - name: Check vision requirements
          id: reqs_vis
          uses: afonsoVale/pipreqs-action@master
          with:
            PROJECT_PATH: ./vision   #default is the root of the repository
            REQUIREMENT_PATH: ./vision/requirements.txt  #default is requirement.txt in the root of your repository 
            PROJECT_NAME: vision
